image:
  file: .gitpod.Dockerfile

# データベースを作成するファイル database.sql を読み込む
# テーブル作成用SQLファイル table.sql を読み込む
# 初期データ initdata.sql を読み込む
# JS 準備
tasks:
  - init: psql           -f ./envdb/database.sql
       && psql -d techdb -f ./envdb/table.sql
       && psql -d techdb -f ./envdb/initdata.sql
       && npm install

# PostgreSQLのポートはユーザ通知を停止
ports:
  - port: 5432
    onOpen: ignore

# Postgresql
# GitHub Pullrequest & Issues
# GitLens
# GitHistory
vscode:
  extensions:
    - ckolkman.vscode-postgres
    - eamodio.gitlens
    - donjayamanne.githistory
    - github.vscode-pull-request-github
